# Generated by Django 2.2.5 on 2019-12-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='medico',
            new_name='medico_id',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='paciente',
            new_name='paciente_id',
        ),
    ]
